### ISSUE TITLE
Avoid exposing process graph to users: user-defined processes

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-api#161]
In the client guideline examples (https://open-eo.github.io/openeo-api/v/0.3.0/guidelines-clients/#workflow-example)
We currently very explicitly create a 'process graph' and then go on to manage a job. For me, a process graph has always been a technical detail that a 'remote sensing' user does not want to see. (Similar to how the  Earth Engine API works.)
I prefer an approach  where the user creates an image collection, or raster data cube, and then goes on to apply a number of transformations to that data cube. IMO this is closer to the mental model that people use when working with local data.
Note that we do not that these options are not exclusive: we can have a layered client API where what is currently in the guidelines is the lower level API, while the 'previous' Python API is the higher level API, (that relies on the lower level API). So this would mean extending the guidelines.
@bgoesswe Do you think this would be a good approach for the Python API?

**Comment by m-mohr** [comment]
I get the point and support that we should simplify more for less tech-savvy users. Still you need to create the process graph at least internally and somehow pass it to the job. 

A problem with implementing your approach is that we don't really have grouped processes so that the clients don't know easily which processes they can apply to raster cubes for example and which they can't. They can guess by the parameters and return values, but guesses could be wrong.

Also, process graphs are still a part of our "language", because you can still store and re-use process graphs so either need to be aware of them anyway or we need to rename them for the clients (e.g. rename `listProcessGraphs` to a more generic `listAlgorithm`).

I think this issue is a bit too complex to discuss here. I'd like to have a discussion between client developers regarding the client dev guidelines anyway so maybe we can just have a call in the next days? Could also be done in the dev telco next week if it is interesting for a broader audience, but the discussion will be very technical, I think.

**Comment by edzer** [comment]
Would be happy to join that call!

**Comment by jdries** [comment]
Great, I'm available for a call this week! Perhaps thursday or friday? (Or should we simply use the regular dev telco?)
I'm also a fan of grouping some core processes into a profile, otherwise you simply end up with zero interoperability.

**Comment by m-mohr** [comment]
I send an email to you all to find a date on Thu or Fri. If anybody else wants to join, please let me know.

**Comment by m-mohr** [comment]
This issue came up again in #216 and comes up also in other scenarios. If we'd like to hide *process graph* as term from users, we need a different name for it. Currently, process graph is used everywhere throughout the API and is exposed to the users in the clients, the processes (e.g. run_process_graph) etc.

**Comment by m-mohr** [comment]
We were discussing this issue today in the dev telco. Process graph seems to be confusing for users, Peter (EURAC) gave an example from a recent course. 

We thought about better names and had several ideas in mind:
* Workflow (or openEO Workflow)
* Process Chain

Other ideas that were not liked so much:
* Algorithm (the processes are algorithms)
* Task (too similar to job)
* Job (would conflict with batch job)

My personal favorite would be (openEO) Workflow. Other thoughts?

**Comment by przell** [comment]
My personal perception is that "workflow" is a term every user should be familiar with and can relate to as a series of tasks being performed to solve a problem. 
I am neglecting the fact of renaming and the effort related to it since I am not an expert on this side. So this is purely the view of a non-technical-expert users perspective.

**Comment by m-mohr** [comment]
@edzer What is "the process"? In openEO terms we usually use process to refer to a specific process, e.g. "load_collection". Therefore that would be conflicting. Is a process description the description of an individual process or our process graph? Therefore, I don't think it's a good idea to use "process description" as a name.

**Comment by GreatEmerald** [comment]
"Process chain" is much better than a "process graph" because it implies that it's a chain of processes, which is easy for users to understand because that's what they are doing: writing `process().process().process()` etc., in other words chaining processes together.

"Workflow" is fine too, perhaps more marketable, but a bit less clear in what it entails as opposed to "process chain".

**Comment by edzer** [comment]
_workflow_ and _chain_ are both too abstract.

**Comment by m-mohr** [comment]
For me as a user, it is not intuitively clear what the difference between process and process description could be. Process description also sounds more like the metadata describing the process. But if we use the same term (process for pre-defined processes and process graphs), then they need to behave the same way, which is not the case in the moment. So a stored process graph from a user must be usable in the same way as the pre-defined reduce for example. This is currently not the case and therefore it would be confusing to give them the same name. So we have two options:

1. We could make it happen that a user could store process graphs as user-defined processes at /processes (i.e. merge /process_graphs and /processes) and they would be listed and handled exactly as pre-defined processes.
2. If we want to have pre-defined processes and process graphs to be differently handled, then we need different names to avoid confusion.

The first option has some charm, but needs quite some changes on the API and in implementations. The second option with a different name would be the cheap and easy solution, but we'd need to name it workflow or process chain or ...

Opinions?

**Comment by mkadunc** [comment]
It seems to me we’re trying to reinvent language for what is usually called a ‘program’ or a ‘function’ in programming, so maybe drawing some analogies might help:
- function has an *identifier* (name) that provides means of addressing it from the outside (we have process_id and process-graph-id and UDF-id for this)
- function has a *signature* (identifier with parameters and sometimes types and return value) that specifies how one can use it (built-in processes and UDFs provide this in OpenEO, but not user-defined process graphs)
- function is usually implemented within its *body* (or function*definition*), which specifies code that, when run, would perform the work promised by that function and produce its result (in openEO, we represent bodies of custom processes with “process graphs”, bodies of UDFs with ‘native’ code, and we don’t expose bodies of built-in processes)
- all programming environments have some *built-in* functions whose signature is known, but whose body is usually not accessible, or of interest, to most programmers or users
- most programming environments allow programmers (users) to define their own functions (by providing both signature and body) and use these in the same way they use the built-in functions - that’s the core mechanism that enables writing software at ever higher levels of abstraction (openEO allows custom processes, but has slightly different rules for using built-in vs. custom vs. UDF processes)
- a lot of programming environments provide human-readable *description* alongside built-in functions, as a way of explaining the intent and functionality of the function and instructing the programmer on how to use it
- most programmers that use a function should not care about its body (internals of the flow that produces the result, or even the language that the body is written in) - they should get all the information they need from the function’s contract (signature and documentation)

With these points in mind, here’s my opinion:
- we should not use “graph” to refer to custom functions, because it puts the spotlight onto the particular protocol that was used to define the “body” of the function, i.e. the thing that the user is least concerned about - users should care about inputs and outputs of a function/process, not this
- we could use “process” for all function-like constructs in openEO without them all being exactly the same - we can still talk about built-in processes vs. user-defined processes vs. user-defined native processes; we use an adjective to separate different kinds of similar thing, we don’t have to use different nouns (process vs. graph vs. 
function)
- i would like to see a future when processes could be used by people without them knowing or caring whether they were built-in or custom defined via openEO graph or via Python code; but it seems like a stretch to achieve this at this point, so I’m OK having slightly different behaviour for each of the three

**Comment by aljacob** [comment]
Hi everybody,

I am coming in late to the discussion as I was very busy the last couple of weeks. From my point of view, this discussion is missing a bit the point of the original problems, that were addressed by @jdries and that also @przell brought up, after his experience of using the R-client with non EO users during a workshop here at Eurac.

First of all I don't think it is necessary or improving anything if we are now renaming definitions in the API. Why do I think this? Because we have to consider who our users are. The user of the API for example for sure is not the user of the client library. The API is only used by back-end and client developers. We can assume that those are experts on the matter and have a very good understanding of what a graph is. Using a fuzzy word like work-flow or chain will not lead to better implementations, because then it will not be clear to the developers what they have to implement. 

On the other hand we have consumer of the openEO client libraries and web interface as in the editor. The people we have here, possibly have less knowledge of what a graph is and probably in most cases never need to know that either. So here I support what @jdries said in his original issue formulation. In the environment of the client libraries I believe after some experience of trying them out myself, the most important thing is to keep them as original as possible, to what is custom in the corresponding user domain, so be as pythonic as possible in the way you write code in python, as R'ish as possible when working with R and as Javascripty as possible when working with the js client. From my perspective this mean, that things do not necessarily need to be done in exactly the same way in all clients, nor do they need to be called the same thing.

Important is then, that the client delivers are perfectly valid graph to the back-end so that the back-end knows what to do.

Regarding the exposure of the graph in the client, I think it makes sense to be able to see that on request, but not something, that should be put in front of the user by default. 

Regarding @mkadunc I think you are right and I would also love to see a seamless integration of different types of functions in the graph at some point and I agree that all the user has to care about are to understand what to put in a process and what he retrieves from it as a result.

Maybe we should after we have these concepts clear for ourselves also make sure to communicate them in that way, to the various type of users we have.

**Comment by m-mohr** [comment]
> * i would like to see a future when processes could be used by people without them knowing or caring whether they were built-in or custom defined via openEO graph or via Python code; but it seems like a stretch to achieve this at this point, so I’m OK having slightly different behaviour for each of the three

Would you be all up to implement this even if it means backward-incompatible changes to the process graphs in the next version? I checked how it could be implemented and it seems it's not too difficult. We only need to merge the concept of process graph variables and callback parameters. Both is already in the API and just needs to be merged and potentially even makes the implementation easier. This would lead us to a future where a custom stored process graph could be referenced as process in the process graph. I think this would make the whole user experience much smoother.

Regarding the naming this would lead to just calling process graphs "user-defined processes" (although this may be confused with UDFs) or so.

**Comment by m-mohr** [comment]
The only issue I see is that variables currently work on a global scope and from_argument is strictly available in its scope.

![](https://user-images.githubusercontent.com/8262166/68859591-e5276e00-06e7-11ea-8376-2cfe86356051.jpg)

**Comment by m-mohr** [comment]
We'll try the approach with process graphs bein user-defined processes. 
Scope: parameters can be accessed also by children, but only in the same "file"/"json".
Afterwards we can remove run_process_graph

**Comment by m-mohr** [comment]
Started work, here are the changes to the user documentation: https://github.com/Open-EO/openeo.org/commit/7377f22dd098539120d3ab7c985e57df95a9a7b2

**Comment by m-mohr** [comment]
A user-defined process will now simply be a process with the same schema as predefined processes in /processes, but with an additional key `process_graph`. The process graph is required, all other fields are optional. This allows us having self-contained processes, makes the /process_graphs aligned with processes and process graphs (no separate schema needed) and let's us drop user-defined processes into process graphs easily. It's a bit of work to get there, but I think it really makes the API much better overall. PR is coming soon.
