### ISSUE TITLE
What if a process is not available? (Core Profiles)

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-api#2]
In the proof of concept API calls, there's always a check if the needed processes are available in the endpoint. This is entirely similar how OGC standards do things, but in practice, this is hardly ever used. Mainly because:
- in a client script, the developer does not 'declare' what functions he will be using later on
- The endpoint will return an error anyway when an unsupported function is used, so better to do error handling there?

Another way to allow optional implementations in backends, is to group functionality into profiles. For instance, a 'core' profile that is obligatory, and then optional stuff for specific use cases?

**Comment by appelmar** [comment]
These calls are indeed superfluous if users know the processes they are using in their scripts (as in the proof of concept). I think these calls could be useful rather as documentation when users e.g. need to know which arguments processes expect. Another idea could be to let client packages automatically find out which processes are available when users connect to a back-end and then automatically generate python / R / JS functions to call the processes. Introducing something like a core profile with standard process definitions sounds very helpful to me in that regard.

**Comment by m-mohr** [comment]
The discovery is also useful for the (JS) editor to build a list of options, but indeed practically it probably won't be used much by the users itself. Maybe that's something for the clients to incorporate that in an intelligent way. The core profiles sound like a good idea, but probably not for the proof of concept yet => 1.0.0.

**Comment by GreatEmerald** [comment]
This sounds like two separate issues, actually. The first one is more on error handling: if the backend sends an informative enough error, then there's no reason for clients to check whether the function is implemented or not beforehand. The problem is that each backend needs to send an informative enough error about it (HTTP 501 is pretty standard, but that might not be enough).

The second issue is the core profile idea. It does indeed sound reasonable to define a core profile, so that those functions are predefined in clients to increase user-friendliness. But at the same time, making it mandatory doesn't sound reasonable either, there may be valid cases where a backend would only implement a very small subset of the functionality (e.g. only filtering for backends that only do data retrieval and not processing). And then there's the question of which processes should be part of the core profile, and where/how to document it.

**Comment by m-mohr** [comment]
Yes, indeed. The first issue will probably be solved with #36 (at least I plan to do so). The second issue is discussed here. 

 Regarding profiles: I thought of them as predefined set of processes that a back-end can support or can't. They'll specify what profiles and additional processes they implement. It's probably easier for users to just check whether profiles x and y are available on a server rather than checking the availability for a set of dozens of processes.

**Comment by GreatEmerald** [comment]
I don't really see much direct benefit to users here. Users' needs are very diverse. If they have a script that uses a dozen of processes, they need a backend that supports those processes; profiles are only relevant to the point of "if I only use these processes, I will be able to run this on more backends". If anything, figuring out which processes are part of the profile is already something that users would not really want to do (but at least that can be made easy with good documentation).

For clients, on the other hand, it's quite important because that defines which functions should be predefined and by default available to users, and which shouldn't be.

**Comment by m-mohr** [comment]
Just had another idea regarding profiles. Maybe they should be extensible, e.g. backend could provide their own profiles and the /processes endpoint could just link to them in case it is fully supported.

GET /processes could return:
```
[
  {
    "process_id": "NDVI",
    "description": "Computes the normalized difference vegetation index (NDVI) for all pixels of the input dataset."
  },
  {
    "profile_id": "core",
    "version": "1.0",
    "url": "http://openeo.org/api/v1/profiles/core"
  }
]
```

GET /profiles/core would return a set of processes that is defined similarily to GET /processes or so. We could describe our "core profile" like this, too, and don't need to put all this core profile stuff in the API specification itself.

Just a short idea on a sunday morning that I wanted to write down for discussion.

**Comment by GreatEmerald** [comment]
Do you mean that the backends would be able to define that they support the core profile, and then not have to define what exactly the core profile is because it's the same for all backends? That would indeed cut down on the duplication of work between all backends, though then you also need a central place to define all the core processes.

Not sure about mixing the profile and process definitions together in `/processes`, though. That seems a bit more difficult to parse as opposed to having a separate endpoint for listing profile support.

Also, what happens if a backend implements the majority, but not all, of the core profile? They would then need to manually define all those processes and duplicate the work again until they get into full compliance with the core profile... Perhaps in that case it should be possible to define support for individual processes out of a profile, e.g. have a `process_id` + `profile_id` etc. in one process definition?

**Comment by m-mohr** [comment]
Yes, we would need a central openeo.org back-end (supporting only profiles) for this, not sure whether that's a good idea or not.

About partial implementation: Shouldn't happen in the best case, but if needed it could be defined like this:
```
  {
    "profile_id": "core",
    "version": "1.0",
    "url": "http://openeo.org/api/v1/profiles/core",
    "unsupported": ["filter_bands", "ndvi"]
  }
```

But that's definitely something we need to discuss in depth, was more a quick idea on a Sunday morning. ;)

**Comment by GreatEmerald** [comment]
Well, there was also a discussion of making a central W*S server so that every backend wouldn't need to make their own, so the centralised nature might not be an issue (and it seems to work for XML with DTDs, too).

Interesting idea with exclusion. Though reading it seems like the backend supports the core profile, but in reality, it's not fully compliant with the core profile, just individual processes are.

**Comment by m-mohr** [comment]
Regarding the error handling: This has been fixed with #36 . Simply send openEO an error with error code 2101.

Profiles are still in discussion though.

**Comment by m-mohr** [comment]
Im not sure whether we still need the profiles. We'll define many processes centrally anyway, but still need the full definition available to the API, e.g. for the process graph builder in R or the visual model builder in JS. We may just set up a central place where processes are defined and the back-ends can link to it in the process description (like JSON references in JSON schema). This way we avoid duplication. Profiles are maybe not flexible enough and won't cover the user needs. Also the idea regarding "unsupported" seems counter-intuitive. To find back-ends supporting all processes they can use the openEO hub (see https://github.com/Open-EO/openeo-hub/issues/1, bullet point 3) or the validation endpoint and don't need to go through the processes itself.

**Comment by GreatEmerald** [comment]
Hm, true, if the processes are defined centrally and there's a tool to find which backends support the user's required functionality, then that would solve the issue without needing to have profiles. On the other hand, having a set of processes that are important (so that new backends would focus on those first) would still be handy, but it's true that it doesn't need to be in the API itself.

**Comment by m-mohr** [comment]
I thought it is clear and required to have a set of central processes anyway and we are just figuring out who and when to do them, see also the e-mail discussion on "[openEO] needed discussion on process definition". Otherwise interoperability would not be really possible anyway, which would mean we failed our mission.

**Comment by m-mohr** [comment]
I just revisited this issue and this isn't really an issue any longer. 

* We have a central list of processes, which back-ends should follow. The list defines, which are recommended to be implemented and which are optional.
* Due to the comprehensive process descriptions in /processes it is easy to validate process graphs and allows us to figure whether a back-end can run the process graph or not.
* We have openEO Hub in development, which allows easy searching for back-ends based on a submitted process graph.

All in all, I think we don't really need profiles (or we could see the process categories as profiles).
