### ISSUE TITLE
Process graph definition

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-api#20]
We should write a comprehensive description about process graphs.
It should mention how they are defined (as this is not possible in Swagger 2.0) and what they can include. 
For example, it is not really made clear how to incorporate and run UDFs.

Based on a comment from Dainius:
> On UDFs: all right, that makes sense, and indeed "runtimes" or "capabilities" makes it more clear. If UDFs themselves are executed by passing them in process graphs, then the API documentation still doesn't make that clear: there are `udf_description` objects that would seem to be related to that, but in reality they seem to be simply more in-depth descriptions of UDF types. And then I don't see anything in the `process_graph` object that refers to UDFs either. So how exactly would the API calls look in order to define a UDF and use it?

**Comment by edzer** [comment]
I think a good timing for this might be when we have the prototypes running in M6, and can reflect on them.

**Comment by m-mohr** [comment]
Yes, that sounds reasonable. For the proof-of-concept it should be enough to have the examples at https://open-eo.github.io/openeo-api-poc/poc/index.html as the basis for the implementation. Otherwise we need to improve the examples there until everybody speaks "the same language".

**Comment by m-mohr** [comment]
Additionally, we might need to specify (core?) processes including their parameters to improve interoperability.

Relates to: #32 (export options), #2 (core profiles)

**Comment by m-mohr** [comment]
Started working on this matter in the file [ddocs/docs/processgraphs.md](docs/docs/processgraphs.md).

**Comment by GreatEmerald** [comment]
Is this connected to https://open-eo.github.io/openeo-api-poc/processgraphs/index.html?

Because @flahn noticed that that page does not actually follow the "tree" process graph definition (see https://github.com/Open-EO/openeo-r-client/issues/14), it is not using an array for each imagery argument. Is the documentation incorrect, or should backends be able to handle both variants with an array or just a single element, or..?

**Comment by m-mohr** [comment]
Yes, it is connected.

The page mentions in the part about the Argument Set that both is theoretically allowed. In practice the process definition defines what is allowed/expected. Usually it expected just a single image collection but processes like `join` might define to allow an array of image collections.

**Comment by GreatEmerald** [comment]
I see. So is the expectation that the backends should support both `imagery` as a single element as well as an array, or that the backends are free to support only either of the two because the processes and the imagery are all defined by the backends themselves? Either way this is something that should probably be documented...

**Comment by m-mohr** [comment]
The back-ends should support whatever their processes require them to support. While parsing the process graph a back-end doesn't need to know `imagery` as a name at all. It needs to know the content of the arguments (e.g. does it contain a `product_id` or a `process_id`?).

From my point of view that is documented, but that is just me with my background knowledge from creating the API. ;-) If there is something unclear or needs to be improved I need your input, please.

**Comment by GreatEmerald** [comment]
Hm, so then it's the latter... That might be problematic for clients, because unless #47 is done, there is no way to tell what format is expected for each argument, whether the backend can handle only arrays or single elements or both for any given process. Same issue with the `imagery` argument, really: if it's called something else in a given process, the clients have no idea what they should be sending.

It's also a standardisation issue: what if you have two backends that support a `filter_bbox` process, but one of them can only handle arrays and the other one can only handle single elements? For either the `imagery` or the `bbox` argument...

**Comment by m-mohr** [comment]
Yes, sure. That is at least a documentation task and needs #47 to be solved after POC. For the POC all processes I am aware of are using single elements, no arrays. I don't fully agree with the `imagery` related comment though. The name is known by calling `GET /processes/{process_id}`. That will be cumbersome though.

> It's also a standardisation issue: what if you have two back-ends that support a filter_bbox process, but one of them can only handle arrays and the other one can only handle single elements? For either the imagery or the bbox argument...
That should not happen, core processes are pre-defined. Therefore the expected input for both imagery and bbox is known. bbox can't take an array anyway according to the specification.

In the end it's all about agreeing on a specification where clients and back-ends need to agree on. If a back-end doesn't follow the spec., then it's simply not compatible.

**Comment by GreatEmerald** [comment]
Well, @aljacob's backend assumed `imagery` to be an array; that's really the whole question here, is that something that the backends are allowed to decide on their own, or if this is something that should be standard across all backends.

As for `imagery` with another name: sure, the name is known, but not the functionality; if clients see that the first argument is supposed to be `collections`, should they send the same thing as they normally do for `imagery`, or format it differently? What if it's not the first argument, but the last one? Again that needs #47 to be solved. But then that's a discussion for that issue I suppose.

Yes, the core processes will be well-defined (thankfully!), but I was just using that as an example. What if there's a non-core process, so it's not formally defined anywhere, but it's nevertheless popular and used on at least two backends? If the argument definitions diverge, that would make users' code non-portable between backends, even though the same functionality is provided by both. (But then this is probably a separate issue too.)

**Comment by m-mohr** [comment]
> when did we actually change this?
There were inconsistencies in the docs/spec and then I decided to one of the alternatives. Seems there was also some knowledge lost during the transition between Marius and me. In the end this will be (is) solved with #47. I think there is nothing left to do with regards to process graphs...
