### ISSUE TITLE
Visualization examples

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-api#211]
In the recent workshop, people first tried to visalize data, but that wasn't very trvilal. Therefore we should ensure there's an easy way to visualize data. Multiple ideas come to mind:
1. Have an visualization example in the collection metadata
2. Have something like a view_collection process that can simply visualize data with some parameters to set.
3. Implement load_collection and save_result in a way that it can visualize without any further processes
4. ...?

**Comment by sinergise-anze** [comment]
Since part of every visualization should be a legend, I would like to suggest another idea: 

4.  it would be nice if the system could generate legends (images) directly from visualization metadata (that is: how the values translate to colors).

Not sure if it helps, but for examples on how legends are defined in Sentinel Hub see [this page](https://www.sentinel-hub.com/faq/how-define-custom-legend).

**Comment by lforesta** [comment]
are we talking about visualization of all data in the cube_view specified in the process graph? This may be a lot, but maybe a back-end could retunr small previews with coarser resolution perhaps?

**Comment by m-mohr** [comment]
Nothing specifically. We are free to choose the best path to go. We could link to previews and/or have visualization defaults in the metadata that save_result can use and/or ...?

**Comment by m-mohr** [comment]
What I'll do here is to allow collection-level assets from STAC. This allows us to link to thumbnails or visualization process graphs from the collections.
