### ISSUE TITLE
Unable to use process "absolute" using Visual Model in GEE

### ISSUE THREAD

**Issue by prateekbudhwar** [Open-EO/openeo-api#230]
When I try to connect the output from a callback in Reduce process to the "absolute" process it gives an error "Types are not Compatible"

**Comment by m-mohr** [comment]
What are the schemas for both the absolute parameter and the reduce callback parameter in your back-end? It is likely that they are not compatible and need to be fixed.

**Comment by prateekbudhwar** [comment]
@m-mohr I meant that it also doesnt work on GEE backend too, nothing to do with EURAC backend for now.

**Comment by m-mohr** [comment]
Oh, I just realized that absolute is not valid because it is defined for a *single* number, but the callback parameter in reduce returns an *array* of numbers. That's not compatible, of course. absolute is just not a reducer. Depending on your use case you could use apply and absolute, but that's not a reducer, too. You still need to reduce the array to a single number.

As this is not a Web Editor issue, I'm closing here. Feel free to contact me by other means to discuss the issue regarding the processes.
