### ISSUE TITLE
optional process parameters

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-api#303]
https://github.com/Open-EO/openeo-api/blob/12471721d9c74262ae962f7ad6c746ac77aad382/openapi.yaml#L4797-L4809

What's the usefulness of having this `optional` field for process parameters? Isn't it enough to set or not set the `default` field in practice? 
It seems to add unnecessary overhead for backends and users (in case of user defined processes).

**Comment by m-mohr** [comment]
There are some processes (quantiles, array_element at the moment) that have an "either or" requirement (e.g. "q" or "probabilities" in "quantiles). They don't have a default value specified, but they are technically specified as optional though they throw an error if none the parameters is specified. I can't remove the optional flag there as otherwise validations would fail.

In general, it's just a bit more explicit. I don't think all users immediately understand that a default value means optional. And then it's also because other specs do it similarly (it's OpenAPI and WPS inspired).

**Comment by soxofaan** [comment]
background story: I'm working on user-defined process support in python client and VITO backend, and one question I have is about this flow: 
- user stores a UDP with a parameter with a default value, but does not enable the "optional" flag (because setting a default value seems to imply that)
- user calls the UDP without specifying the parameter, assuming the default value will be used
- should the backend fail because the parameter is missing and not optional? 

seems like unnecessary annoyance towards the user.


Possible solutions:
- in clients: automatically enable `optional` when `default` is set
- change meaning of `optional`: "Determines whether this parameter is optional to be specified even when no default is specified. When a default is specified, the parameter is automatically to be considered optional"

**Comment by m-mohr** [comment]
Thanks for the clarification. I was more thinking about pre-defined processes (where it originates from), but for user-defined processes it's a bit unclear indeed. 

For UDP I'd indeed think that default values should be used although the parameter is required. The issue mostly comes from the default meaning for optional being required. Previously, by default things were optional but there were some issues with that in pre-defined processes so I changed that. That was before UDP came up and now I realize the change is a bit of an issue there. Without reverting to the old behavior, I think your last suggestion could work. It should be clarified on the API side.
