### ISSUE TITLE
Job results assets recommendation

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-api#363]
https://github.com/Open-EO/openeo-api/blob/81dd248b9e8b8caeedbdd96c6a9dd8f3f56d0eb7/openapi.yaml#L3576-L3577

I don't get what this is about.
Should there be an additional `link` property in the asset object? Or is it about the `links` of the whole response object? And in what sense would this allow users to publish data more easily?

**Comment by m-mohr** [comment]
Hmm, it was meant to make clients download the results as a "STAC" catalog/item. Now that we have #359, I can probably rephrase this and just ask clients to also store the response with the assets and other STAC files so that the stored data has all metadata and data and thus is a valid STAC catalog locally.

**Comment by m-mohr** [comment]
I've made some changes to clarify the behavior, see the commit above. It's in the PR for STAC Collections as Job Results: #359
