### ISSUE TITLE
URL Prefix uncertainties

### ISSUE THREAD

**Issue by mmacata** [Open-EO/openeo-api#386]
The spec tells how and when to use the URL version prefix [here](https://openeo.org/documentation/1.0/developers/api/reference.html#operation/connect): 

From this I understand that only `/` for capabilities and `/.well-known/openeo` need to be available without API prefix, all other endpoints must be available at `/api/v1.0/` and not without version prefix. If `/.well-known/openeo` is not reachable, `/` should return the [Capabilities](https://openeo.org/documentation/1.0/developers/api/reference.html#tag/Capabilities).

Is my understanding correct? If so, I would suggest to explain this directly in the [API Principles](https://openeo.org/documentation/1.0/developers/api/reference.html#section/API-Principles) section as some important endpoints are already specified above the "Supported openEO versions" section and from e.g. [Authentication](https://openeo.org/documentation/1.0/developers/api/reference.html#section/Authentication) it is not obvious that the prefix must to be used.

**Comment by m-mohr** [comment]
No, this is not entirely correct. Everything except `/.well-known/openeo` is recommended to be versioned.

If you click the dropdown for the endpoint path, you get the details, see for example:

![image](https://user-images.githubusercontent.com/8262166/116395973-12f16b80-a825-11eb-9e20-c662070251a3.png)

![image](https://user-images.githubusercontent.com/8262166/116396032-27356880-a825-11eb-911f-b47a0ed14c37.png)

**Comment by m-mohr** [comment]
> If `/.well-known/openeo` is not reachable, `/` should return the [Capabilities](https://openeo.org/documentation/1.0/developers/api/reference.html#tag/Capabilities).

Please not that the part you are referring to here is for the clients:

> If the request to the well-known URI fails, the client SHOULD try to request the capabilities at / from https://example.com.

This is just a hint at clients how to work if well-known discovery has not been implemented. That was mostly for the initial time when back-ends did not had well-known discovery. Back-ends don't necessarily need to serve anything at /.

Example: You may host your homepage at http://mundialis.de and have well known discovery at http://mundialis.de/.well-known/openeo so that clients can just use http://mundialis.de to connect as this is sometimes nicer than http://whatever-subdomain.aws.com (in cast you have some kind of API on AWS). The API then could still live at http://whatever-subdomain.aws.com, but that detail would be hidden to the user.

**Comment by mmacata** [comment]
Ok, thanks for clarification. I never saw the small dropdown arrow icon next to the API URL field! This was the missing piece.
