### ISSUE TITLE
Specify behaviour for math on heterogenous images

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-api#4]
When computing, for instance, the difference between a PROBA-V image and a Sentinel Image, which have e a different projection and resolution, we basically have two options:

1. User is responsible for ensuring that the pixels match, by first applying resampling
2. User simply applies function, driver takes care of doing the right thing (GEE does this)

This is a quite important design choice, so we'll need to discuss this and put it in the spec.

**Comment by m-mohr** [comment]
Yes, this is indeed important, but can probably be ignore for the proof-of-concept.
My first impression is that choosing alternative 2 is the better choice in terms of simplicity. Many users probably won't want to mess around with that topic.

**Comment by m-mohr** [comment]
Due to the fact that we have the constraints (fka data views) in our spec, it is reasonable to go with alternative 2. For now, I added an explanation to the documentation (see https://open-eo.github.io/openeo-api/v/0.3.0/views/index.html). If there are any reasons against the suggested back-end behavior, please let us know.
