### ISSUE TITLE
Clarification on PUT /process_graphs

### ISSUE THREAD

**Issue by Ardweaden** [Open-EO/openeo-api#449]
https://docs.openeo.cloud/api/#tag/User-Defined-Processes/operation/store-custom-process

Documentation states:

> The id MUST be unique for the authenticated user, including all pre-defined processes by the back-end.

> id: The identifier for the process. It MUST be unique across its namespace (e.g. pre-defined processes or user-defined processes).

I assume the second one is correct? I see there are some new proposals that will handle it that way. 

Additionally
> Clients SHOULD warn the user if a user-defined process is added with the same identifier as one of the pre-defined process.

Not sure why this is stated here, but the back-end does not need to warn, correct?

Thanks for help.

**Comment by m-mohr** [comment]
Yes, it's the latter, but as a back-end I'd still implement to check whether a user process would conflict with a pre-defined process just to avoid confusion.

The note for clients is there because the API docs are for clients and back-ends. :-) As such, there are also some guidelines specifically for clients. Back-ends don't need to warn (but I'd personally reject them as mentioned above).
