### ISSUE TITLE
openEO Processes version not listed in capabilities

### ISSUE THREAD

**Issue by bschumac** [Open-EO/openeo-api#474]
Currently looking on [https://api.openeo.org/#tag/Capabilities ](https://api.openeo.org/#tag/Capabilities ) I am wondering why there is no openeo-processes version listed in the response schema. Shouldn't there be a linkage between the openeo api version and the openeo-processes version that is minimally required?

**Comment by m-mohr** [comment]
There is none because you could in principle have processes from multiple versions exposed. The version of a process is also not very relevant as processes describe themselves and clients should not rely on specific versions but instead work based on what they actually receive as process description.
