### ISSUE TITLE
PUT   '/process_graphs/{process_graph_id}' response

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-api#498]
PUT  '/process_graphs/{process_graph_id}' 
https://github.com/Open-EO/openeo-api/blob/c5a45b4647b06e313a4f099e9119bfa3cca5c6a3/openapi.yaml#L2426-L2429

defines 200 response, but does not define its content type. Other 200 responses have:
```
          content:
            application/json:
```

Is there a body in that response, or isn't there (and should it be a 201/202 or 204?)

**Comment by soxofaan** [comment]
(came up while automatically parsing the api doc in context of  https://github.com/Open-EO/openeo-python-client/issues/439)

**Comment by m-mohr** [comment]
This is intentional:
1. No response body as for most other resources that create (POST /services etc)
2. 201 usually are accompanied by a Location header to show where the resource lives and which ID has been generated. Here, this is not required as the ID is provided and known by the user. Also, the PUT method is used here to Create and Update. So 200 seemed a bit more reasonable than 201. Both would be fine, but changing it now would be breaking.
