### ISSUE TITLE
Conventions for client libraries

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-api#81]
Users (at EODC Forum) wanted to know, whether the client libraries of Python, JS and R will follow the same structure and conventions. That means, whether the function names / upper and lower case / objects / the whole syntax will be equal (as far as possible) for the three clients. That could lead to an easier transfer between the programming languages. The alternative is following the distinct language conventions, which may lead to a higher acceptance of using openEO by the distinct user groups.

Should we define centrally specified conventions for client libraries? @flahn @jdries 
Edit: See https://open-eo.github.io/openeo-api/v/0.3.0/guidelines-clients/index.html

**Comment by m-mohr** [comment]
@christophfriedrich commented:
> I'd encourage to name functions exactly the same in all languages since this project is all about standardisation. If we are concerned about the acceptance by developers it might be an option to supply aliases that reflect the language-specific conventions.

**Comment by m-mohr** [comment]
I think the general workflow (i.e. creating a session, then loading an image collection, then calling processes, etc.) and structure (i.e. classes etc) should be the same. Currently it is different. The naming should be also the same, but I would agree on casing differences. As an example: in PHP it is more common to write `obj->filter_bands`, but in Java it would probably be `obj.filterBands`. As long as it is consistent that already makes a difference and adopts to different style guides.

**Comment by GreatEmerald** [comment]
I think there could be a bit of both. In some cases, the differences in naming are rather arbitrary, indeed. But we do want to make it as native and as close to the established conventions as possible for user-friendliness.

Also, in some cases the clients can only follow the API (e.g. for core profile processes), which is also not always ideal/most user-friendly.

Another consideration would be consistency with other, already established software, i.e. Google Earth Engine. If we use the same conventions, it will be easier for GEE users to migrate.

Perhaps it would be useful to inventory function names and decide on what would make the most sense. For the R client, we already have such an inventory: https://github.com/Open-EO/openeo-r-client/wiki/Development-Overview-v0.2.x Something like this could be done centrally with all the clients, so that it would be easier to compare and choose what makes the most sense.

**Comment by m-mohr** [comment]
This issue has been raised multiple time during the Hackathon. Seems to be a very important issue and we should make sure to get this right for the next version.

**Comment by m-mohr** [comment]
I created a page where we can work on client library conventions. I'll write down proposals there in the next time and you are more than welcome to add stuff, suggest improvements etc.
Link: https://open-eo.github.io/openeo-api/v/0.3.0/guidelines-clients/index.html

**Comment by m-mohr** [comment]
I started working on client library guidelines: https://open-eo.github.io/openeo-api/v/0.3.0/guidelines-clients/ 
It's a first draft and I'd be very happy to get feedback on that.

**Comment by GreatEmerald** [comment]
Your example of `R (functional style)` is not actually functional. The PGB is OO. You should provide the actual functional style, i.e. instead of:
```R
pgb = con %>% pgb()
processgraph = pgb$getCollection(name = "Sentinel-2A") %>% 
  pgb$filterBbox(east = 652000, west = 672000, north = 5161000, south = 5181000, srs = "EPSG:32632") %>%
  pgb$filterDaterange(extent = c("2017-01-01T00:00:00Z", "2017-01-31T23:59:59Z")) %>%
  pgb$NDVI(nir = "B4", red = "B8A") %>%
  pgb$minTime()
```
Use:
```R
processgraph = collection(name = "Sentinel-2A") %>% 
  process("filterBbox", east = 652000, west = 672000, north = 5161000, south = 5181000, srs = "EPSG:32632") %>%
  process("filterDaterange", extent = c("2017-01-01T00:00:00Z", "2017-01-31T23:59:59Z")) %>%
  process("NDVI", nir = "B4", red = "B8A") %>%
  process("minTime")
```
For that matter, you could also collapse all pipes `%>%` into the first argument of the next function. That would also be closer to what R users are used to, but it would also make it much more messy (especially the process graph building).

Another thing to keep in mind: don't use common function names, such as `connect`, `version` and `currency`, that will likely conflict with something existing. Case in point, `version()` usually gives the version of the interpreter. Prefix it with something instead.

I was also wondering about Google Earth Engine compatibility. I think there would be value in adopting some of their terminology when it makes sense, so that it is easier for users to switch to openEO.

**Comment by m-mohr** [comment]
Thank you @GreatEmerald for your input!

> Your example of `R (functional style)` is not actually functional. The PGB is OO. You should provide the actual functional style

I'm not an R programmer and just adopted what I found in the R client documentation. I changed the guideline for 0.4.0 as you proposed.

> For that matter, you could also collapse all pipes `%>%` into the first argument of the next function. That would also be closer to what R users are used to, but it would also make it much more messy (especially the process graph building).

Not sure about that one. I'll leave that decision up to the R devs (@flahn  and you). Just tell me how you think it should be.

> Another thing to keep in mind: don't use common function names, such as `connect`, `version` and `currency`, that will likely conflict with something existing. Case in point, `version()` usually gives the version of the interpreter. Prefix it with something instead.

Yes, if there are problems with name collisions the methods should be prefixed. You can already see that in the PHP example, where it is `openeo_version()` for example.

> I was also wondering about Google Earth Engine compatibility. I think there would be value in adopting some of their terminology when it makes sense, so that it is easier for users to switch to openEO.

Especially for the processes, I'll check back with Google Earth Engine (see also my mail from today). And as always, I'm open to suggestions if you think there is something we can further do to improve.

**Comment by m-mohr** [comment]
> Another thing to keep in mind: don't use common function names, such as `connect`, `version` and `currency`, that will likely conflict with something existing. Case in point, `version()` usually gives the version of the interpreter. Prefix it with something instead.

@GreatEmerald At least version() was renamed to clientVersion() and shouldn't be conflicting with version() in R. Still, it is totally fine to use a prefix and name this functions openeo_client_version, openeo_connect() etc.

**Comment by m-mohr** [comment]
Will be evaluated in separate issues.
