### ISSUE TITLE
Uniform process_graph_id, and job_id generation across different backends

### ISSUE THREAD

**Issue by arcostarusty** [Open-EO/openeo-api#95]
As addressed during the last biweekly development prints it would be a useful feature for the handling of processes if the ID’s, in particular the process_graph_id and eventually also the job_id would be uniformly generated across the different backends. This would make the handling of distributed processes somehow simpler in particular also when performing comparison tests across different backends, i.e a given process can be generated a accessed via the same id on all backends.

In a scenario where a process is created and launched on different backends, that may reside on different clouds for example, having a uniformly created UUID would be also easier to handle or debug in a kind of Task scheduler implementation.

One possible combination would be to use the following scheme

process_graph_id = hash(sha256(process_graph + [*user_id?]))

Where some fields of the process_graph, if necessary, could also be omitted in order to generalise further, for example             "from":"2017-01-01", "to":"2017-01-31"

job_id = hash(process_graph_id + #instance_sequence_nr))

This would allow for example a unique, uniform and directional mapping between process_graph (eventually per user) and job_id.

**Comment by m-mohr** [comment]
Thanks for your suggestion. I see that there is a potential benefit in this suggestion, but after thinking about it for quite some time I found some problems:

**Problem 1**
There will be different hashes for process graphs that do the exact same thing:
`{process_id:"load_data", args:{data_id:"sentinel-2b"}}` => `A5FB857320F01BAADBC03D3B63DC101060CF917144E1A06375355D9D4D37510C`
`{"process_id":"load_data","args":{"data_id":"sentinel-2b"}}` => `4AF118D6654C4A388C9F07041EB4D2F147708834E9A02E8B6C71A1AC2929410B`

This means, you'd need to normalize the JSON somehow, e.g. by making them compliant to either RFC4627, RFC7159 or ECMA-404.

**Problem 2**
The same process_graph could lead to different results due to user-uploaded files. The following process graph depends on the user-uploaded file for polygons, but different users can upload files to their individual workspace with the same name, but different content:
```
{
  "process_id":"zonal_statistics",
  "args":{
    "regions":"polygon.json"
  }
}
```
Don't see a reasonable / user-friendly solution for this.

**Problem 3**
IMO `process_graph_id = hash(sha256(process_graph + [*user_id?]))` won't work as the user ID won't be the same across back-ends and therefore the generated IDs will be different and therefore incomparable. What you actually would need is something like:  `process_graph_id = sha256(process_graph) + divider +  UUID`
A similar thing applies to the proposed job_id generation. The instance_sequence_nr must be outside of the hashing method and could be something like: `job_id = process_graph_id + divider +  UUID`

**Conclusion**
I DO see the benefit in this suggestion, but IMO the implementation cost seems to be too high in comparison to what we gain from it. Problem 1 seems to be very hard to solve in consistent way across different languages. I don't see a reasonable solution for problem 2 at all. Problem 3 is easy to solve. Until anyone has a reasonable solution for the problems, I'd leave this out of the spec and keep it simple. Other opinions?

I'll happily re-open this issue again if anybody has solutions for 1 or 2.

**Comment by arcostarusty** [comment]
Yes, I also agree that according to your considerations this is difficult to handle and makes things too complex. Better keep things simpler.

Thank  you for the analysis and considerations

Cheers,

Armin
